### ISSUE TITLE
 module 'bottleneck' has no attribute '__version__' after running python3 demo_app1.py

### ISSUE THREAD

**Issue by MNCTTY** [meownoid/face-identification-tpe#22]
Hello! I faced the issue 

```
python3 demo_app1.py 
Using TensorFlow backend.
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "demo_app1.py", line 24, in <module>
    from model import FaceVerificator
  File "/Users/mnctty/Documents/___Jupyter_Notebooks___/face-identification-tpe/model.py", line 6, in <module>
    from cnn import build_cnn
  File "/Users/mnctty/Documents/___Jupyter_Notebooks___/face-identification-tpe/cnn.py", line 1, in <module>
    from keras.layers import Flatten, Dense, Dropout
  File "/usr/local/lib/python3.6/site-packages/Keras-2.2.5-py3.6.egg/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python3.6/site-packages/Keras-2.2.5-py3.6.egg/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/usr/local/lib/python3.6/site-packages/Keras-2.2.5-py3.6.egg/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/usr/local/lib/python3.6/site-packages/Keras-2.2.5-py3.6.egg/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/usr/local/lib/python3.6/site-packages/Keras-2.2.5-py3.6.egg/keras/backend/load_backend.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python3.6/site-packages/Keras-2.2.5-py3.6.egg/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/site-packages/tensorflow/__init__.py", line 30, in <module>
    from tensorflow._api.v2 import compat
  File "/usr/local/lib/python3.6/site-packages/tensorflow/_api/v2/compat/__init__.py", line 21, in <module>
    from tensorflow._api.v2.compat import v1
  File "/usr/local/lib/python3.6/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 643, in <module>
    'tensorflow_estimator.python.estimator.api._v1.estimator'))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/tools/component_api_helper.py", line 56, in package_hook
    child_pkg = importlib.import_module(child_package_str)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/usr/local/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/usr/local/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/usr/local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/usr/local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 53, in <module>
    from tensorflow_estimator.python.estimator.inputs import inputs
  File "/usr/local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/inputs/inputs.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.inputs.numpy_io import numpy_input_fn
  File "/usr/local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/inputs/numpy_io.py", line 26, in <module>
    from tensorflow_estimator.python.estimator.inputs.queues import feeding_functions
  File "/usr/local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/inputs/queues/feeding_functions.py", line 40, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/usr/local/lib/python3.6/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.categorical import Categorical
  File "/usr/local/lib/python3.6/site-packages/pandas/core/categorical.py", line 36, in <module>
    from pandas.core.base import (PandasObject,
  File "/usr/local/lib/python3.6/site-packages/pandas/core/base.py", line 20, in <module>
    import pandas.core.nanops as nanops
  File "/usr/local/lib/python3.6/site-packages/pandas/core/nanops.py", line 30, in <module>
    ver = bn.__version__
AttributeError: module 'bottleneck' has no attribute '__version__'
```

only if I restart mac, bottleneck solves its problem, but always when I run python3 demo_app1.py , it appears again

Do you know what it can be? It seems to me an unsolvable

**Comment by meownoid** [comment]
https://disk.yandex.ru/d/16GictwI3ANWHv

**Comment by meownoid** [comment]
Repository is now archived, closing all issues.
